version: "3.10"

services:
  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
#      - "db:5432"
    environment:
      - SECRET_KEY=django-insecure-4p%-v14=xj)wem==*dw6vyaklsb*h0d=@fc0r1t15z1#sefo2l
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=saeid
      - DB_PASS=1qaz!QAZ
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=saeid
      - POSTGRES_PASSWORD=1qaz!QAZ
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - db
      - backend


volumes:
  static_volume:
  media_volume:
  postgres_data:
